name: Check Push

on:
  push:
    branches: [ "main" ]
    paths:
      - "lib/**"
      - "lesson_02/quiz/**"
      - "lesson_03/quiz/**"
      - "lesson_04/expression/**"
      - "lesson_05/types/**"
      - "lesson_06/conditionals/**"
      - "lesson_07/objects/**"
      - "lesson_08/collections/**"
      - "lesson_09/oop/**"
      - "lesson_10/examples/**"
      - "lesson_10/quiz/**"
      - "lesson_10/solid/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build Lesson 02 with Gradle Wrapper
      working-directory: ./lesson_02/quiz
      run: ./gradlew assemble

    - name: Build Lesson 03 with Gradle Wrapper
      working-directory: ./lesson_03/quiz
      run: ./gradlew check

    - name: Build Lesson 04 with Gradle Wrapper
      working-directory: ./lesson_04/expression
      run: ./gradlew assemble

    - name: Build Lesson 05 with Gradle Wrapper
      working-directory: ./lesson_05/types
      run: ./gradlew check

    - name: Build Lesson 06 with Gradle Wrapper
      working-directory: ./lesson_06/conditionals
      run: ./gradlew assemble && ./gradlew spotlessCheck

    - name: Build Lesson 07 with Gradle Wrapper
      working-directory: ./lesson_07/objects
      run: ./gradlew assemble && ./gradlew spotlessCheck

    - name: Build Lesson 08 with Gradle Wrapper
      working-directory: ./lesson_08/collections
      run: ./gradlew assemble && ./gradlew spotlessCheck

    - name: Build Lesson 09 with Gradle Wrapper
      working-directory: ./lesson_09/oop
      run: ./gradlew check

    - name: Build Lesson 10 Quiz with Gradle Wrapper
      working-directory: ./lesson_10/quiz
      run: ./gradlew check

    - name: Build Lesson 10 Examples with Gradle Wrapper
      working-directory: ./lesson_10/examples
      run: ./gradlew check

    - name: Build Lesson 10 Solid with Gradle Wrapper
      working-directory: ./lesson_10/solid
      run: ./gradlew check

    - name: Build Lesson 12 Solid with Gradle Wrapper
      working-directory: ./lesson_12/io
      run: ./gradlew assemble && ./gradlew spotlessCheck

    - name: Build Shared Lib with Gradle Wrapper
      working-directory: ./lib/java/codedifferently-instructional
      run: ./gradlew check


